import mongoose from 'mongoose';
import dotenv from 'dotenv';
import Job from './models/Job.js';
import Candidate from './models/Candidate.js';

dotenv.config();

const seedDatabase = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('Connected to MongoDB');

    await Job.deleteMany({});
    await Candidate.deleteMany({});
    console.log('Cleared existing data');

    const jobs = await Job.create([
      {
        title: 'Senior Frontend Developer',
        department: 'Engineering',
        location: 'San Francisco, CA',
        openPositions: 2,
        hiringManager: 'Sarah Johnson',
        description: 'We are looking for an experienced frontend developer with expertise in React and TypeScript.',
        requirements: ['React', 'TypeScript', '5+ years experience', 'CSS/Tailwind'],
      },
      {
        title: 'Full Stack Engineer',
        department: 'Engineering',
        location: 'New York, NY',
        openPositions: 3,
        hiringManager: 'Mike Chen',
        description: 'Build scalable web applications using MERN stack. Work with modern DevOps practices.',
        requirements: ['Node.js', 'React', 'MongoDB', 'Docker', '3+ years experience'],
      },
      {
        title: 'Product Manager',
        department: 'Product',
        location: 'Remote',
        openPositions: 1,
        hiringManager: 'Emma Davis',
        description: 'Lead product strategy and roadmap for our SaaS platform.',
        requirements: ['Product Management', 'Stakeholder Management', '5+ years', 'Analytics'],
      },
      {
        title: 'Backend Developer',
        department: 'Engineering',
        location: 'Austin, TX',
        openPositions: 2,
        hiringManager: 'James Wilson',
        description: 'Build robust backend services with Node.js and TypeScript.',
        requirements: ['Node.js', 'TypeScript', 'REST APIs', '3+ years experience'],
      },
      {
        title: 'UI/UX Designer',
        department: 'Design',
        location: 'Los Angeles, CA',
        openPositions: 1,
        hiringManager: 'Lisa Wong',
        description: 'Design beautiful and intuitive user interfaces for our web applications.',
        requirements: ['Figma', 'UI Design', 'UX Research', '4+ years experience'],
      },
      {
        title: 'DevOps Engineer',
        department: 'Infrastructure',
        location: 'Remote',
        openPositions: 2,
        hiringManager: 'Robert King',
        description: 'Manage and optimize our cloud infrastructure and CI/CD pipelines.',
        requirements: ['Docker', 'Kubernetes', 'AWS', 'CI/CD', '4+ years experience'],
      },
    ]);

    console.log('Created sample jobs:', jobs.length);

    const candidates = await Candidate.create([
      {
        jobId: jobs[0]._id,
        name: 'Alex Thompson',
        email: 'alex.thompson@email.com',
        currentRole: 'Frontend Engineer',
        company: 'Tech Solutions Inc',
        experience: 6,
        stage: 'Interview',
        matchScore: 92,
        skills: ['React', 'TypeScript', 'Tailwind CSS'],
        notes: ['Strong candidate with excellent portfolio', 'Previous experience with MERN stack'],
        interviewStatus: 'Scheduled',
        interviewDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
      },
      {
        jobId: jobs[0]._id,
        name: 'Jordan Martinez',
        email: 'jordan.m@email.com',
        currentRole: 'React Developer',
        company: 'StartupXYZ',
        experience: 3,
        stage: 'Shortlisted',
        matchScore: 85,
        skills: ['React', 'JavaScript', 'CSS'],
        notes: ['Good technical skills', 'Needs TypeScript experience'],
        interviewStatus: 'Pending',
        interviewDate: null,
      },
      {
        jobId: jobs[0]._id,
        name: 'Casey Wilson',
        email: 'casey.wilson@email.com',
        currentRole: 'Junior Frontend Developer',
        company: 'Web Agency Pro',
        experience: 1,
        stage: 'Applied',
        matchScore: 68,
        skills: ['React', 'HTML/CSS'],
        notes: ['Junior developer', 'Good learning potential'],
        interviewStatus: 'Not Started',
        interviewDate: null,
      },
      {
        jobId: jobs[0]._id,
        name: 'Emma Rodriguez',
        email: 'emma.r@email.com',
        currentRole: 'Senior UI Developer',
        company: 'Design Studio',
        experience: 7,
        stage: 'Offered',
        matchScore: 90,
        skills: ['React', 'TypeScript', 'Next.js', 'Tailwind CSS'],
        notes: ['Excellent UI expertise', 'Has led frontend teams before'],
        interviewStatus: 'Completed',
        interviewDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
      },
      {
        jobId: jobs[1]._id,
        name: 'Morgan Lee',
        email: 'morgan.lee@email.com',
        currentRole: 'Full Stack Developer',
        company: 'Cloud Systems Ltd',
        experience: 7,
        stage: 'Offered',
        matchScore: 95,
        skills: ['Node.js', 'React', 'MongoDB', 'Docker'],
        notes: ['Excellent full-stack developer', 'Ready to join immediately'],
        interviewStatus: 'Completed',
        interviewDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
      },
      {
        jobId: jobs[1]._id,
        name: 'Taylor Brown',
        email: 'taylor.brown@email.com',
        currentRole: 'Backend Engineer',
        company: 'Enterprise Corp',
        experience: 5,
        stage: 'Interview',
        matchScore: 88,
        skills: ['Node.js', 'React', 'PostgreSQL', 'AWS'],
        notes: ['Strong backend skills', 'Currently learning React'],
        interviewStatus: 'Scheduled',
        interviewDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000),
      },
      {
        jobId: jobs[1]._id,
        name: 'Riley Anderson',
        email: 'riley.anderson@email.com',
        currentRole: 'Senior Full Stack Engineer',
        company: 'Tech Giants Inc',
        experience: 8,
        stage: 'Hired',
        matchScore: 94,
        skills: ['Node.js', 'React', 'MongoDB', 'Docker', 'Kubernetes'],
        notes: ['Hired!', 'Starting next month'],
        interviewStatus: 'Completed',
        interviewDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
      },
      {
        jobId: jobs[1]._id,
        name: 'David Chen',
        email: 'david.chen@email.com',
        currentRole: 'Full Stack Developer',
        company: 'Web Solutions',
        experience: 4,
        stage: 'Applied',
        matchScore: 72,
        skills: ['Node.js', 'React', 'Express', 'MongoDB'],
        notes: ['Career changer from bootcamp', 'Eager to learn'],
        interviewStatus: 'Not Started',
        interviewDate: null,
      },
      {
        jobId: jobs[2]._id,
        name: 'Sam Patel',
        email: 'sam.patel@email.com',
        currentRole: 'Senior Product Manager',
        company: 'SaaS Unicorn',
        experience: 6,
        stage: 'Interview',
        matchScore: 87,
        skills: ['Product Strategy', 'Analytics', 'Leadership'],
        notes: ['Product manager from B2B SaaS background', 'Excellent track record'],
        interviewStatus: 'Scheduled',
        interviewDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000),
      },
      {
        jobId: jobs[2]._id,
        name: 'Nicole Santos',
        email: 'nicole.s@email.com',
        currentRole: 'Product Manager',
        company: 'Growth Ventures',
        experience: 4,
        stage: 'Shortlisted',
        matchScore: 80,
        skills: ['Product Management', 'User Research', 'Data Analysis'],
        notes: ['Strong PM fundamentals', 'Experience with B2B products'],
        interviewStatus: 'Pending',
        interviewDate: null,
      },
      {
        jobId: jobs[3]._id,
        name: 'Kevin Zhang',
        email: 'kevin.z@email.com',
        currentRole: 'Senior Backend Developer',
        company: 'Finance Systems',
        experience: 7,
        stage: 'Interview',
        matchScore: 91,
        skills: ['Node.js', 'TypeScript', 'PostgreSQL', 'API Design'],
        notes: ['Expert in scalable backend systems', 'Experience with microservices'],
        interviewStatus: 'Scheduled',
        interviewDate: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000),
      },
      {
        jobId: jobs[3]._id,
        name: 'Sarah Mitchell',
        email: 'sarah.m@email.com',
        currentRole: 'Backend Developer',
        company: 'Tech Startup',
        experience: 3,
        stage: 'Applied',
        matchScore: 76,
        skills: ['Node.js', 'JavaScript', 'Express', 'MongoDB'],
        notes: ['Solid backend fundamentals', 'First role outside startup'],
        interviewStatus: 'Not Started',
        interviewDate: null,
      },
      {
        jobId: jobs[3]._id,
        name: 'Marcus Johnson',
        email: 'marcus.j@email.com',
        currentRole: 'Principal Engineer',
        company: 'Large Enterprise',
        experience: 10,
        stage: 'Offered',
        matchScore: 96,
        skills: ['Node.js', 'TypeScript', 'System Design', 'AWS'],
        notes: ['Extremely experienced', 'Looking for new challenges'],
        interviewStatus: 'Completed',
        interviewDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
      },
      // UI/UX Designer candidates
      {
        jobId: jobs[4]._id,
        name: 'Lisa Park',
        email: 'lisa.park@email.com',
        currentRole: 'UX Designer',
        company: 'Design Co',
        experience: 5,
        stage: 'Interview',
        matchScore: 89,
        skills: ['Figma', 'User Research', 'Prototyping', 'Interaction Design'],
        notes: ['Strong design portfolio', 'Great at user research'],
        interviewStatus: 'Scheduled',
        interviewDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
      },
      {
        jobId: jobs[4]._id,
        name: 'James Foster',
        email: 'james.f@email.com',
        currentRole: 'Junior UI Designer',
        company: 'Creative Agency',
        experience: 2,
        stage: 'Shortlisted',
        matchScore: 70,
        skills: ['Figma', 'UI Design', 'Adobe XD'],
        notes: ['Good design sense', 'Needs more UX experience'],
        interviewStatus: 'Pending',
        interviewDate: null,
      },
      {
        jobId: jobs[5]._id,
        name: 'Christopher Lee',
        email: 'chris.lee@email.com',
        currentRole: 'Senior DevOps Engineer',
        company: 'Cloud Infrastructure Inc',
        experience: 8,
        stage: 'Interview',
        matchScore: 93,
        skills: ['Docker', 'Kubernetes', 'AWS', 'Terraform', 'CI/CD'],
        notes: ['Expert in cloud infrastructure', 'Excellent automation skills'],
        interviewStatus: 'Scheduled',
        interviewDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000),
      },
      {
        jobId: jobs[5]._id,
        name: 'Patricia Wang',
        email: 'patricia.w@email.com',
        currentRole: 'DevOps Engineer',
        company: 'Tech Firm',
        experience: 4,
        stage: 'Applied',
        matchScore: 78,
        skills: ['Docker', 'AWS', 'Linux', 'GitHub Actions'],
        notes: ['Solid DevOps fundamentals', 'Limited Kubernetes experience'],
        interviewStatus: 'Not Started',
        interviewDate: null,
      },
      {
        jobId: jobs[5]._id,
        name: 'Richard Brown',
        email: 'richard.b@email.com',
        currentRole: 'Infrastructure Manager',
        company: 'Enterprise Systems',
        experience: 9,
        stage: 'Hired',
        matchScore: 97,
        skills: ['Docker', 'Kubernetes', 'AWS', 'GCP', 'Automation'],
        notes: ['Hired!', 'Will lead infrastructure team'],
        interviewStatus: 'Completed',
        interviewDate: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000),
      },
    ]);

    console.log('Created sample candidates:', candidates.length);

    console.log('✅ Database seeded successfully!');
    process.exit(0);
  } catch (error) {
    console.error('❌ Error seeding database:', error.message);
    process.exit(1);
  }
};

seedDatabase();
